version: "3"

services:
  {{package}}:
    container_name: {{package}}
    image: {{package}}
    build:
      context: .
      args:
        EXTRAS: "[test]"
    tty: true
    entrypoint: ["bash"]
    environment:
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
    volumes:
      - .:/{{package}}
      - ../indipoc:/indipoc